export const zkPayrollPrivateAbi = [
  {
    type: "function",
    name: "createPayroll",
    inputs: [
      { name: "proof", type: "uint256[8]" },
      { name: "totalAmount", type: "uint256" },
      { name: "activeCount", type: "uint256" },
      { name: "commitments", type: "uint256[5]" },
      { name: "recipients", type: "address[5]" },
    ],
    outputs: [{ name: "payrollId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimPayment",
    inputs: [
      { name: "payrollId", type: "uint256" },
      { name: "commitmentIndex", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "salt", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "reclaimUnclaimed",
    inputs: [{ name: "payrollId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getCommitments",
    inputs: [{ name: "payrollId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256[5]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRecipients",
    inputs: [{ name: "payrollId", type: "uint256" }],
    outputs: [{ name: "", type: "address[5]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isClaimed",
    inputs: [
      { name: "payrollId", type: "uint256" },
      { name: "index", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPayrollInfo",
    inputs: [{ name: "payrollId", type: "uint256" }],
    outputs: [
      { name: "employer", type: "address" },
      { name: "totalAmount", type: "uint256" },
      { name: "activeCount", type: "uint256" },
      { name: "claimedCount", type: "uint256" },
      { name: "claimedAmount", type: "uint256" },
      { name: "createdAt", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextPayrollId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paymentToken",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PayrollCreated",
    inputs: [
      { name: "payrollId", type: "uint256", indexed: true },
      { name: "employer", type: "address", indexed: true },
      { name: "totalAmount", type: "uint256", indexed: false },
      { name: "activeCount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentClaimed",
    inputs: [
      { name: "payrollId", type: "uint256", indexed: true },
      { name: "commitmentIndex", type: "uint256", indexed: true },
      { name: "recipient", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FundsReclaimed",
    inputs: [
      { name: "payrollId", type: "uint256", indexed: true },
      { name: "employer", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  { type: "error", name: "InvalidProof", inputs: [] },
  { type: "error", name: "InvalidInputs", inputs: [] },
  { type: "error", name: "InvalidTotalAmount", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
  { type: "error", name: "AlreadyClaimed", inputs: [] },
  { type: "error", name: "InvalidClaim", inputs: [] },
  { type: "error", name: "PayrollNotFound", inputs: [] },
  { type: "error", name: "TooEarly", inputs: [] },
  { type: "error", name: "Unauthorized", inputs: [] },
  { type: "error", name: "NothingToReclaim", inputs: [] },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
] as const;
