// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title IPoseidonT4
/// @notice Interface for the Poseidon hash function with 3 inputs (T=4)
/// @dev The actual implementation is deployed from EVM bytecode generated by circomlibjs
interface IPoseidonT4 {
    function poseidon(uint256[3] memory input) external pure returns (uint256);
}
